export default emoji = [
  {
    status1: "hạnh phúc",
    icon1: "🙂",
    status2: "có phúc",
    icon2: "😇",
  },
  { status1: "được yêu", icon1: "🥰", status2: "buồn", icon2: "🙁" },
  { status1: "đáng yêu", icon1: "🥰", status2: "biết ơn", icon2: "😃" },
  { status1: "hào hứng", icon1: "🤩", status2: "đang yêu", icon2: "😍" },
  { status1: "điên", icon1: "🤪", status2: "cảm kích", icon2: "😄" },
  { status1: "sung sướng", icon1: "☺️", status2: "tuyệt vời", icon2: "😁" },
  { status1: "ngốc nghếch", icon1: "😋", status2: "vui vẻ", icon2: "🥳" },
  { status1: "tuyệt vời", icon1: "🙂", status2: "thật phong cách", icon2: "😎" },
  { status1: "thú vị", icon1: "🙂", status2: "thư giãn", icon2: "😩" },
  { status1: "positive", icon1: "🙂", status2: "rùng mình", icon2: "😱" },

];
export const StatusToEmoji = {
  "hạnh phúc": "🙂",
  "có phúc": "😇",
  "được yêu": "🥰",
  "buồn": "🙁",
  "đáng yêu": "🥰",
  "biết ơn": "😃",
  "hào hứng": "🤩",
  "đang yêu": "😍",
  "điên": "🤪",
  "cảm kích": "😄",
  "sung sướng": "☺️",
  "tuyệt vời": "😁",
  "ngốc nghếch": "😋",
  "vui vẻ": "🥳",
  "tuyệt vời": "🙂",
  "thật phong cách": "😎",
  "thú vị": "🙂",
  "thư giãn": "😩",
  "positive": "🙂",
  "rùng mình": "😱",
  "đầy hy họng": "😇",
  "hân hoan": "😊",
};